
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SENDDATA = "SENDDATA";
export const SENDDATA_SUCCESS = "SENDDATA_SUCCESS";
export const SENDDATA_FAILED = "SENDDATA_FAILED";

export const UPDATE10QUESTION = "UPDATE10QUESTION";
export const UPDATE10QUESTION_SUCCESS = "UPDATE10QUESTION_SUCCESS";
export const UPDATE10QUESTION_FAILED = "UPDATE10QUESTION_FAILED";

export const UPDATE20QUESTION = "UPDATE20QUESTION";
export const UPDATE20QUESTION_SUCCESS = "UPDATE20QUESTION_SUCCESS";
export const UPDATE20QUESTION_FAILED = "UPDATE20QUESTION_FAILED";

export const UPDATE30QUESTION = "UPDATE30QUESTION";
export const UPDATE30QUESTION_SUCCESS = "UPDATE30QUESTION_SUCCESS";
export const UPDATE30QUESTION_FAILED = "UPDATE30QUESTION_FAILED";

export const UPDATE40QUESTION = "UPDATE40QUESTION";
export const UPDATE40QUESTION_SUCCESS = "UPDATE40QUESTION_SUCCESS";
export const UPDATE40QUESTION_FAILED = "UPDATE40QUESTION_FAILED";

export const UPDATE50QUESTION = "UPDATE50QUESTION";
export const UPDATE50QUESTION_SUCCESS = "UPDATE50QUESTION_SUCCESS";
export const UPDATE50QUESTION_FAILED = "UPDATE50QUESTION_FAILED";

export const UPDATE60QUESTION = "QUESTION60QUESTION";
export const UPDATE60QUESTION_SUCCESS = "QUESTION60QUESTION_SUCCESS";
export const UPDATE60QUESTION_FAILED = "QUESTION60QUESTION_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
